[package]
name = "bootctl"
description = "Development host-side CLI for GoreeCloud Boot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
gcboot-core = { path = "../gcboot-core" }

[lints]
workspace = true
